CREATE DATABASE IPI_2;

USE IPI_2;

/*CRIANDO TABELA SOMENTE PARA ILUSTRAÇÃO, TEM MAIS REGRAS DE RELACIONAMENTO E RESTRIÇÕES */

CREATE TABLE TB_CEP(
    ID_CEP INT PRIMARY KEY AUTO_INCREMENT,
    CEP VARCHAR 		(8) NOT NULL,
    RUA VARCHAR 		(100) NOT NULL,
    NUMERO VARCHAR 		(4) NOT NULL,
    COMPLEMENTO VARCHAR 	(50),
    BAIRRO VARCHAR 		(50) NOT NULL,
    CIDADE VARCHAR 		(50) NOT NULL,
    UF CHAR 			(2) NOT NULL
);
	CREATE TABLE NOME(
    ID_NOME 	INT PRIMARY KEY AUTO_INCREMENT,
    NOME        VARCHAR(255) NOT NULL,
    DATANASCE 	DATETIME NOT NULL,
    EMAIL 		VARCHAR(255) NOT NULL,
    TELEFONE 	VARCHAR(15) NOT NULL,
    CPF 		VARCHAR(11) NOT NULL,
    RG 			VARCHAR(15) NOT NULL
);
	CREATE TABLE MENSAGEM(
    ID_MENSAGEM 	INT PRIMARY KEY AUTO_INCREMENT,
  	ASSUNTO   	    VARCHAR(255) NOT NULL,
    MENSAGEM        VARCHAR(255) NOT NULL,
    SENHA           VARCHAR(8) NOT NULL
);






